### PR TITLE
WIP: Network sitemeta

### LINKED ISSUE #2: Feature request: Add 'wp_sitemeta' on multisite
It would be great if you could think about adding 'wp_sitemeta' to the plugin.
It represents *_site_option() (I know, you know ;-)) and would help when debugging/development for multisite.

### PR DESCRIPTION
**Pull request by cfoellmann**
- [x] add page in network admin
- [x] add plugin action link to network page
- [ ] Extend `manager_add_option()` for sitemeta
- [ ] Extend `manager_delete_options()` for sitemeta
- [ ] Extend `manager_ajax_update_option_callback()` for sitemeta
- [ ] Setup identifiers for core sitemeta keys
- [ ] Refine/cleanup code

@mikeselander I did some grunt work but some of the code is very unelegant. Maybe you can pitch in and help me get this ready sooner

Closes #2

### CODE REVIEW

**Comment by cfoellmann** [comment]
this is rebased and back on track.
I am really up to fixing this up

**Comment by cfoellmann** [comment]
I will get to this first.
It will solve some real pains for me.

@mikeselander you on board with this?

**Comment by mikeselander** [comment]
I am OK with the concept, although we might want to consider some re-architecting first to make this much easier.

**Comment by cfoellmann** [comment]
not having a working Settings API in the network admin is a b*
I dont know if I have got the time to refactor in a major way. I was about to "wing" it... 😈

**Pull request closed without merging**
